import fp from 'fastify-plugin';
import type { FastifyPluginAsync } from 'fastify';
import type { PrismaClient } from '@deckgauge/db';
import { evaluatePolicy, type ConnectionModel, type Policy } from './policy.js';

declare module 'fastify' {
  interface FastifyContextConfig {
    policy?: Policy;
    connectionModel?: ConnectionModel;
    /**
     * Stamped by this plugin's own `onRoute` hook, so it is true for exactly
     * the routes that sit inside the context whose `preHandler` below does the
     * enforcing. Declaring a policy and *being checked against it* are two
     * different things — a route registered outside this scope would look
     * fully declared in the route inventory and never be checked. Never set by
     * hand; route-inventory.test.ts asserts on it.
     */
    policyEnforced?: boolean;
  }
}

/**
 * Default-deny authorization. Every route must declare `config.policy`; any
 * route missing one prevents the server from starting. Offending routes are
 * collected as they're registered (`onRoute`) and reported together, once, when
 * boot would otherwise complete (`onReady`) — so fixing them doesn't require a
 * boot-per-offender cycle. Enforcement itself happens in a preHandler.
 */
export function buildPolicyPlugin(
  prisma: PrismaClient,
  opts: { singleUser: boolean },
): FastifyPluginAsync {
  return fp(async (app) => {
    const unguarded: string[] = [];

    app.addHook('onRoute', (route) => {
      // HEAD is auto-generated by Fastify for GET routes and inherits its config.
      if (route.method === 'HEAD') return;
      if (!route.config?.policy) {
        unguarded.push(`${route.method} ${route.url}`);
        return;
      }
      // This hook and the preHandler below share one encapsulation context, so
      // reaching here is proof the route is actually enforced — see the
      // `policyEnforced` doc above.
      route.config = { ...route.config, policyEnforced: true };
    });

    app.addHook('onReady', async () => {
      if (unguarded.length === 0) return;
      throw new Error(
        `${unguarded.length} route(s) declare no authorization policy:\n` +
          unguarded.map((r) => `  ${r}`).join('\n') +
          `\nAdd config: { policy: … } to each — see apps/api/src/auth/policy.ts.`,
      );
    });

    app.addHook('preHandler', async (request, reply) => {
      const policy = request.routeOptions.config?.policy;
      if (!policy) {
        request.log.error({ url: request.url }, 'route reached preHandler with no policy');
        return reply.code(500).send({ error: 'Misconfigured route' });
      }
      const result = await evaluatePolicy(
        { prisma, singleUser: opts.singleUser },
        policy,
        {
          user: request.user ? { id: request.user.id } : null,
          params: request.params as Record<string, string | undefined>,
          query: request.query as Record<string, string | undefined>,
          body: request.body,
          connectionModel: request.routeOptions.config?.connectionModel,
          isAdmin: request.isAdmin === true,
          canViewAnalytics: request.canViewAnalytics === true,
          log: request.log,
        },
      );
      if (!result.ok) return reply.code(result.status).send({ error: result.error });
    });
  });
}
