import fp from 'fastify-plugin';
import type { FastifyPluginAsync } from 'fastify';
import type { PrismaClient } from '@deckgauge/db';
import { evaluatePolicy, type Policy } from './policy.js';

declare module 'fastify' {
  interface FastifyContextConfig {
    policy?: Policy;
    /**
     * Stamped by this plugin's own `onRoute` hook, so it is true for exactly
     * the routes that sit inside the context whose `preHandler` below does the
     * enforcing. Declaring a policy and *being checked against it* are two
     * different things — a route registered outside this scope would look
     * fully declared in the route inventory and never be checked. Never set by
     * hand; route-inventory.test.ts asserts on it.
     */
    policyEnforced?: boolean;
  }
}

/**
 * Default-deny authorization. Every route must declare `config.policy`; any
 * route missing one prevents the server from starting. Offending routes are
 * collected as they're registered (`onRoute`) and reported together, once, when
 * boot would otherwise complete (`onReady`) — so fixing them doesn't require a
 * boot-per-offender cycle. Enforcement itself happens in a preHandler.
 */
export function buildPolicyPlugin(
  prisma: PrismaClient,
  opts: {
    singleUser: boolean;
    /**
     * Optional edition hook that may re-express a denial. Absent in Community.
     * See enterprise-contract.ts.
     */
    restrictDenial?: (
      denial: { status: number; error: string },
      reason: string,
    ) => { status: number; body: Record<string, unknown> } | null;
  },
): FastifyPluginAsync {
  return fp(async (app) => {
    const unguarded: string[] = [];

    app.addHook('onRoute', (route) => {
      // HEAD is auto-generated by Fastify for GET routes and inherits its config.
      if (route.method === 'HEAD') return;
      if (!route.config?.policy) {
        unguarded.push(`${route.method} ${route.url}`);
        return;
      }
      // This hook and the preHandler below share one encapsulation context, so
      // reaching here is proof the route is actually enforced — see the
      // `policyEnforced` doc above.
      route.config = { ...route.config, policyEnforced: true };
    });

    app.addHook('onReady', async () => {
      if (unguarded.length === 0) return;
      throw new Error(
        `${unguarded.length} route(s) declare no authorization policy:\n` +
          unguarded.map((r) => `  ${r}`).join('\n') +
          `\nAdd config: { policy: … } to each — see apps/api/src/auth/policy.ts.`,
      );
    });

    app.addHook('preHandler', async (request, reply) => {
      const policy = request.routeOptions.config?.policy;
      if (!policy) {
        request.log.error({ url: request.url }, 'route reached preHandler with no policy');
        return reply.code(500).send({ error: 'Misconfigured route' });
      }
      const result = await evaluatePolicy(
        { prisma, singleUser: opts.singleUser },
        policy,
        {
          user: request.user ? { id: request.user.id } : null,
          params: request.params as Record<string, string | undefined>,
          query: request.query as Record<string, string | undefined>,
          body: request.body,
          isAdmin: request.isAdmin === true,
          canViewAnalytics: request.canViewAnalytics === true,
          membership: request.membership ?? null,
          // The same signal the denial path below reads, made available to the
          // `unrestricted` policy. Threaded as a boolean, never the reason string:
          // the evaluator must not be able to branch on WHY an edition restricted
          // this membership, only that it did.
          restricted: request.membershipRestriction !== null,
          log: request.log,
        },
      );
      if (!result.ok) {
        // An edition module may re-express a denial that exists because it
        // restricted this membership — so a caller can learn WHY an action is
        // unavailable, not merely that it is. Community has no such module, so the
        // core's own status and body stand unchanged.
        const reason = request.membershipRestriction;
        if (reason && opts.restrictDenial) {
          const override = opts.restrictDenial({ status: result.status, error: result.error }, reason);
          if (override) return reply.code(override.status).send(override.body);
        }
        return reply.code(result.status).send({ error: result.error });
      }
    });
  });
}
